# -*- coding: utf-8 -*-

"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['./launcher.py']
DATA_FILES = [
    './tessdata',
    './default.json',
    './resource'
]
OPTIONS = {
    'argv_emulation': True,
    'iconfile': './resource/icon.icns',
    'includes': 'PIL, numpy, pandas, cpython',
    'packages': "hf_analysis, "
                "tesserocr, "
                "jieba, "
                "sklearn, "
                "pinyin, "
                "pdf2image, "
                "docx2txt, "
                "textwrap3, "
                "xlsxwriter, "
                "xlrd",
    'plist': {
        'CFBundleName': u"高频词汇分析",
        'CFBundleDisplayName': u"高频词汇分析",
        'CFBundleGetInfoString': "hf_word_analysis",
        # 'CFBundleIdentifier': "",
        'CFBundleVersion': "0.1",
        'CFBundleShortVersionString': "0.1",
        'NSHumanReadableCopyright': u"Copyright © 2020, "
                                    u"Hongcheng Wei, All Rights Reserved"
    }
}

setup(
    app=APP,
    packages=[
        'hf_analysis',
        'hf_analysis/processing',
        'hf_analysis/ui',
    ],
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    zip_safe=False
)
